"""
Application constants
"""

# Message types
MESSAGE_TYPE_TEXT = 'text'
MESSAGE_TYPE_VOICE = 'voice'
MESSAGE_TYPE_VIDEO = 'video'
MESSAGE_TYPE_STEGANOGRAPHIC = 'stego'
MESSAGE_TYPE_PEER_MESSAGE = 'peer_message'
MESSAGE_TYPE_CONNECT = 'connect'
MESSAGE_TYPE_DISCONNECT = 'disconnect'
MESSAGE_TYPE_HEARTBEAT = 'heartbeat'

# Error codes
ERROR_AUTH_FAILED = 'AUTH_FAILED'
ERROR_CONNECTION_FAILED = 'CONNECTION_FAILED'
ERROR_INVALID_MESSAGE = 'INVALID_MESSAGE'
ERROR_ROUTING_FAILED = 'ROUTING_FAILED'
ERROR_ENCRYPTION_FAILED = 'ENCRYPTION_FAILED'

# Protocol constants
PROTOCOL_VERSION = '1.0'
PACKET_MAX_SIZE = 65536  # 64KB
HEARTBEAT_INTERVAL = 30  # seconds
HEARTBEAT_TIMEOUT = 60  # seconds

# Encryption constants
ENCRYPTION_ALGORITHM = 'ChaCha20-Poly1305'
HASH_ALGORITHM = 'SHA256'
KEY_SIZE_BITS = 256
NONCE_SIZE_BYTES = 24

# Network constants
IPv4_BROADCAST = '255.255.255.255'
IPv4_LOOPBACK = '127.0.0.1'
DEFAULT_BUFFER_SIZE = 4096
